# Generated by Django 2.0.3 on 2018-03-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20180325_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='crime',
            name='location_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crime',
            name='street_name',
            field=models.CharField(default='Add street name', help_text='Enter a street name', max_length=300),
        ),
        migrations.AddField(
            model_name='crime',
            name='street_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='block_street_name',
            field=models.CharField(default='Add street name', help_text='Enter a street name', max_length=300),
        ),
        migrations.AddField(
            model_name='location',
            name='block_street_number_begin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='block_street_number_end',
            field=models.IntegerField(default=0),
        ),
    ]
