# Generated by Django 2.0.3 on 2018-03-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_location_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='accept_pickup',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='categories',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(help_text='Enter a city', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='location_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='price_range',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='reservation_available',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='state',
            field=models.CharField(help_text='Enter a state', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='zip_code',
            field=models.CharField(help_text='Enter a zip code', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
