# Generated by Django 2.0.3 on 2018-03-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_auto_20180326_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='crime',
            name='anc',
            field=models.CharField(default='000', help_text='Enter an anc', max_length=5),
        ),
        migrations.AddField(
            model_name='crime',
            name='block',
            field=models.CharField(default='000', help_text='Enter a block', max_length=120),
        ),
        migrations.AddField(
            model_name='crime',
            name='block_group',
            field=models.CharField(default='000', help_text='Enter a block group', max_length=20),
        ),
        migrations.AddField(
            model_name='crime',
            name='census_tract',
            field=models.CharField(default='000', help_text='Enter a census tract', max_length=20),
        ),
        migrations.AddField(
            model_name='crime',
            name='cnn',
            field=models.CharField(default='000', help_text='Enter a model', max_length=10),
        ),
        migrations.AddField(
            model_name='crime',
            name='crimetype',
            field=models.CharField(default='000', help_text='Enter a crime type', max_length=11),
        ),
        migrations.AddField(
            model_name='crime',
            name='date',
            field=models.CharField(default='000', help_text='Enter a date', max_length=19),
        ),
        migrations.AddField(
            model_name='crime',
            name='day',
            field=models.CharField(default='000', help_text='Enter a day', max_length=10),
        ),
        migrations.AddField(
            model_name='crime',
            name='district',
            field=models.CharField(default='000', help_text='Enter a district', max_length=10),
        ),
        migrations.AddField(
            model_name='crime',
            name='end_date',
            field=models.CharField(default='000', help_text='Enter an end date', max_length=22),
        ),
        migrations.AddField(
            model_name='crime',
            name='ew',
            field=models.CharField(default='000', help_text='Enter an ew', max_length=4),
        ),
        migrations.AddField(
            model_name='crime',
            name='hour',
            field=models.CharField(default='000', help_text='Enter a hour', max_length=10),
        ),
        migrations.AddField(
            model_name='crime',
            name='method',
            field=models.CharField(default='000', help_text='Enter a method', max_length=6),
        ),
        migrations.AddField(
            model_name='crime',
            name='minute',
            field=models.CharField(default='000', help_text='Enter a minute', max_length=10),
        ),
        migrations.AddField(
            model_name='crime',
            name='month',
            field=models.CharField(default='000', help_text='Enter a month', max_length=10),
        ),
        migrations.AddField(
            model_name='crime',
            name='neighborhood_cluster',
            field=models.CharField(default='000', help_text='Enter a neighborhood cluster', max_length=20),
        ),
        migrations.AddField(
            model_name='crime',
            name='no1',
            field=models.CharField(default='000', help_text='Enter a number', max_length=10),
        ),
        migrations.AddField(
            model_name='crime',
            name='ns',
            field=models.CharField(default='000', help_text='Enter a ns', max_length=5),
        ),
        migrations.AddField(
            model_name='crime',
            name='optional',
            field=models.CharField(default='000', help_text='Enter an optional numer', max_length=20),
        ),
        migrations.AddField(
            model_name='crime',
            name='psa',
            field=models.CharField(default='000', help_text='Enter a psa', max_length=3),
        ),
        migrations.AddField(
            model_name='crime',
            name='quad',
            field=models.CharField(default='000', help_text='Enter a quad', max_length=9),
        ),
        migrations.AddField(
            model_name='crime',
            name='report_dat',
            field=models.CharField(default='000', help_text='Enter a date', max_length=22),
        ),
        migrations.AddField(
            model_name='crime',
            name='second',
            field=models.CharField(default='000', help_text='Enter a number', max_length=10),
        ),
        migrations.AddField(
            model_name='crime',
            name='shift',
            field=models.CharField(default='000', help_text='Enter a shift', max_length=8),
        ),
        migrations.AddField(
            model_name='crime',
            name='start_date',
            field=models.CharField(default='000', help_text='Enter a start date', max_length=22),
        ),
        migrations.AddField(
            model_name='crime',
            name='voting_precinct',
            field=models.CharField(default='000', help_text='Enter a voting precinct', max_length=20),
        ),
        migrations.AddField(
            model_name='crime',
            name='ward',
            field=models.CharField(default='000', help_text='Enter a ward', max_length=5),
        ),
        migrations.AddField(
            model_name='crime',
            name='x',
            field=models.CharField(default='000', help_text='Enter a number', max_length=10),
        ),
        migrations.AddField(
            model_name='crime',
            name='xblock',
            field=models.CharField(default='000', help_text='Enter an xblock', max_length=20),
        ),
        migrations.AddField(
            model_name='crime',
            name='yblock',
            field=models.CharField(default='000', help_text='Enter a yblock', max_length=20),
        ),
        migrations.AddField(
            model_name='crime',
            name='year',
            field=models.CharField(default='000', help_text='Enter a year', max_length=20),
        ),
        migrations.AlterField(
            model_name='crime',
            name='offense',
            field=models.CharField(help_text='Enter an offense', max_length=26),
        ),
    ]
